---
experiments:
  location_used:
    ['경상대',
      '예천',
      '남제주소내',
      '부산복합자재창고',
      '영월본부',
      '인천수산정수장',
      '하동보건소',
      '신안'
      ]
  
  
  features_used: [
      발전률,
      '기온(°C)',
      '강수량(mm)',
      '풍속(m__s)',
      '습도(%)',
      '증기압(hPa)',
      '현지기압(hPa)',
      '일조(hr)',
      '지면온도(°C)',
      'SO2',
      'CO',
      'O3',
      'NO2',
      'PM10',
      'PM25']
      지점,                       #날씨
      #일시, 
      기온(°C), 
      강수량(mm), 
      풍속(m/s), 
      풍향(16방위), 
      습도(%), 
      증기압(hPa), 
      이슬점온도(°C), 
      현지기압(hPa), 
      해면기압(hPa), 
      일조(hr), 
      일사(MJ/m2), 
      적설(cm), 
      3시간신적설(cm), 
      전운량(10분위), 
      중하층운량(10분위), 
      운형(운형약어), 
      최저운고(100m ), 
      시정(10m), 
      지면상태(지면상태코드), 
      현상번호(국내식), 
      지면온도(°C), 
      5cm 지중온도(°C), 
      10cm 지중온도(°C), 
      20cm 지중온도(°C), 
      30cm 지중온도(°C),
      지역,                     #
      망,
      측정소코드,
      측정소명,
      측정일시,                 #시간!!!!!
      SO2,
      CO,
      O3,
      NO2,
      PM10,
      PM25,
      주소
  ]
  save_npy: True
  dataset_num: 3
#  model: MLP
#  model: LSTM
#  model: GRU
#  model: GC_LSTM
#  model: nodesFC_GRU
  model: PM25_GNN
#  model: PM25_GNN_nosub

train:          #수정 필요
  batch_size: 32
  epochs: 50
  exp_repeat: 10
  hist_len: 1
  pred_len: 24
  weight_decay: 0.0005
  early_stop: 10
  lr: 0.0005

filepath:
  weather_dir: E:/VS_Projects_Graduate/Projects/Fine_Dust_to_Solar_Power/KR_weather
  solar_dir: E:/VS_Projects_Graduate/Projects/Fine_Dust_to_Solar_Power/solar_data
  solar_spec: E:/VS_Projects_Graduate/Projects/Fine_Dust_to_Solar_Power/specification/전국태양광설비정보_v1.csv
  results_dir: E:/VS_Projects_Graduate/Projects/Fine_Dust_to_Solar_Power/results

data:   #수정 필요
  list:
    ['경상대',
      '광양항세방',
      '구미',
      '남동발전_본사사옥',
      '영동',
      '예천',
      '남제주소내',
      '부산복합자재창고',
      '부산복합1단계',
      '부산수처리장',
      '부산신항',
      '부산본부',
      '삼척소내',
      '신인천소내',
      '신인천전망대',
      '신인천해수취수구',
      '영월본부',
      '영월철도부지',
      '위미2리',
      '인천수산정수장',
      '하동공설운동장',
      '하동변전소',
      '하동보건소',
      '하동본부',
      '하동정수장',
      '하동하수처리장',
      '광양항',
      '당진',
      '당진매립장_송악',
      '당진자재창고',
      '동해',
      '수원환경사업소',
      '황금물류센터',
      '세종시폐기물매립장',
      '연성정수장',
      '영암에프원b',
      '대구',
      '신안']
  
  solar_weather_conj:   #태양광, 종관기상, 미세먼지
    [
      [경상대, 진주, [상대동, 238133]],
      [광양항세방, 광양시, [중동, 336352]],
      [구미, 구미, [4공단, 437154]],
      [남동발전_본사사옥, 진주, [상대동, 238133]],
      [영동, 수원, [수내동, 131124]],
      [예천, 영주, [안계면, 437411]],
      [남제주소내, 서귀포, [동홍동, 339121]],
      [부산복합자재창고, 부산, [장림동, 221202]],
      [부산복합1단계, 부산, [장림동, 221202]],
      [부산수처리장, 부산, [장림동, 221202]],
      [부산신항, 부산, [장림동, 221202]],
      [부산본부, 부산, [장림동, 221202]],
      [삼척소내, 울진, [남양동1, 632161]],
      [신인천소내, 인천, [구월동, 823631]],
      [신인천전망대, 인천, [구월동, 823631]],
      [신인천해수취수구, 인천, [구월동, 823631]],
      [영월본부, 영월, [중앙동(강원), 632121]],
      [영월철도부지, 영월, [중앙동(강원), 632121]],
      [위미2리, 서귀포, [동홍동, 339121]],
      [인천수산정수장, 인천, [구월동, 823631]],
      [하동공설운동장, 광양시, [중동, 336352]],
      [하동변전소, 광양시, [중동, 336352]],
      [하동보건소, 광양시, [중동, 336352]],
      [하동본부, 광양시, [중동, 336352]],
      [하동정수장, 광양시, [중동, 336352]],
      [하동하수처리장, 광양시, [중동, 336352]],
      [광양항, 광양시, [중동, 336352]],
      [당진, 서산, [독곶리, 534421]],
      [당진매립장_송악, 서산, [독곶리, 534421]],
      [당진자재창고, 서산, [독곶리, 534421]],
      [동해, 동해, [천곡동, 632151]],
      [수원환경사업소, 수원, [영통동, 131114]],
      [황금물류센터, 광양시, [중동, 336352]],
      [세종시폐기물매립장, 대전, [월평동, 525173]],
      [연성정수장, 인천, [정왕동, 131231]],
      [영암에프원b, 목포, [대불, 336441]],
      [대구, 대구, [호림동, 422171]],
      [신안, 광주, [서석동, 324115]]
    ]
  
  weather_var:
    [
      지점, 
      #일시, 
      기온(°C), 
      강수량(mm), 
      풍속(m/s), 
      풍향(16방위), 
      습도(%), 
      증기압(hPa), 
      이슬점온도(°C), 
      현지기압(hPa), 
      해면기압(hPa), 
      일조(hr), 
      일사(MJ/m2), 
      적설(cm), 
      3시간신적설(cm), 
      전운량(10분위), 
      중하층운량(10분위), 
      운형(운형약어), 
      최저운고(100m ), 
      시정(10m), 
      지면상태(지면상태코드), 
      현상번호(국내식), 
      지면온도(°C), 
      5cm 지중온도(°C), 
      10cm 지중온도(°C), 
      20cm 지중온도(°C), 
      30cm 지중온도(°C)
    ]

  pm_var:
    [
      지역,
      망,
      측정소코드,
      측정소명,
      측정일시,
      SO2,
      CO,
      O3,
      NO2,
      PM10,
      PM25,
      주소
    ]

dataset:
  fmt: "YYYY-MM-DD HH"
  data_start: "2013-01-01 01"
  data_end: "2021-07-31 24"

  #1:
  train_start: "2015-01-01 01"
  train_end: "2016-12-31 24"
  val_start: "2017-01-01 01"
  val_end: "2017-12-31 24"
  test_start: "2018-01-01 01"
  test_end: "2018-12-31 24"